name: Deploy Serverless App

on:
  push:
    branches:
      - main 

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Python Dependencies
        run: |
          cd crud-api
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Deploy with Serverless
        run: |
          cd crud-api
          source venv/bin/activate
          serverless deploy --stage dev
